Improve scalar multiplication performance when group element is constant
arkworks-rs/r1cs-std pull request #33
Opened 2021-01-08 06:05 UTC by Pratyush

2021-01-08 06:45 UTC, ValarDragon requested changes

2021-01-08 06:45 UTC, ValarDragon commented on src/groups/mod.rs
> +        if self.is_constant() {
Can you add comments for what this is doing? (Presumably, computing all the point doubles, and then just doing a series of conditional additions)

2021-01-08 06:45 UTC, ValarDragon commented on src/groups/mod.rs
> +        if self.is_constant() {
Should there be a TODO to evaluate conditional select approaches? e.g. if its N bits, and N is small, do a conditional select between 2^N options

2021-01-08 08:09 UTC, ValarDragon commented on src/groups/mod.rs
> +            result.precomputed_base_scalar_mul_le(
Can there be a comment saying that this is taking the right sum of elements? Its not particularly obvious to me from the function name. (Alternatively if the function took in two parameters instead of an iterator, namely, bases and bits, I think it'd make much more sense)

2021-01-08 18:01 UTC, ValarDragon commented on src/groups/mod.rs
> +            result.precomputed_base_scalar_mul_le(
Sorry, I meant can there be a comment in the line, not the function

2021-01-08 22:59 UTC, Pratyush commented on src/groups/mod.rs
> +        if self.is_constant() {
I think this is resolved now? I added comments to `precompute_base_scalar_mul_le`.

2021-01-08 23:00 UTC, Pratyush commented on src/groups/mod.rs
> +            result.precomputed_base_scalar_mul_le(
I'm not sure it makes sense to add this information here, given that `precomputed_base_scalar_mul_le` already has that information, no?

2021-01-09 00:26 UTC, Pratyush commented on src/groups/curves/short_weierstrass/mod.rs
> +        if other.is_constant() {
This is new code that performs mixed addition if `other` is constant (it doesn't make sense to perform mixed addition when other is not constant, as testing for z = 1 eliminates any saved constraints).

For the constant case this is beneficial as it reduces the constraint weight.

2021-01-09 07:01 UTC, ValarDragon commented on src/groups/mod.rs
> +            result.precomputed_base_scalar_mul_le(
I still think we should change one of function name, or function API, but I guess that can be done in a future PR.

Like perhaps a `precomputed_base` struct, which has a scalar mul.

2021-01-09 07:04 UTC, ValarDragon commented on src/groups/curves/short_weierstrass/mod.rs
> +            self_affine.infinity.select(&Self::zero(), &res)
I feel like most applications of scalar multiplication should be able to know if the base point is zero or not, so should we expose a variant that doesn't have this conditional select? (Or perhaps should we consider having a different CurveVar type in the future for when we statically know the point is non-zero?)

2021-01-09 07:08 UTC, Pratyush commented on src/groups/curves/short_weierstrass/mod.rs
> +            self_affine.infinity.select(&Self::zero(), &res)
The issue is that in many cases the base point is a witness, and so we don't have any guarantees on its correctness (and in fact the correctness guarantees might require a scalar mul, eg: checking a Pedersen commitment). Also, the cost of the conditional select is only 3 constraints per scalar mul, which is pretty low IMO.

2021-01-09 07:11 UTC, Pratyush commented on src/groups/curves/short_weierstrass/mod.rs
> +        unimplemented!("cannot enforce prime order");
This is unrelated to the other changes, but I changed it to unimplemented to prevent folks from accidentally relying on this.

2021-01-09 07:13 UTC, Pratyush commented on src/groups/mod.rs
> +            result = bit.borrow().select(&self_plus_base, &result)?;
The previous code was actually incorrect; it was not noticed because we never invoked this method for Short Weierstrass curves (we only invoked it for Twisted Edwards curves, which have a different specialized impl)

2021-01-09 07:27 UTC, ValarDragon commented on src/groups/curves/short_weierstrass/mod.rs
> +            self_affine.infinity.select(&Self::zero(), &res)
Ah right the scalar multiplication should completely dominate this, agreed its not worth worrying about now. Should we note down somewhere places where we know that we are implement things with slight inefficiencies in some cases, in case someone wanted to eek out constraint performance?

2021-01-09 07:29 UTC, ValarDragon commented on src/groups/curves/short_weierstrass/mod.rs
> +        // (https://eprint.iacr.org/2015/1060).
Can you add a comment that the comments below are line number references to this algo

2021-01-09 07:34 UTC, ValarDragon commented on src/groups/curves/short_weierstrass/mod.rs
> +        let z = (&yy_p_bz3 * &yz_pairs) + xy_pairs * xx3_p_azz; // 31, 32, 33
I think the following style of comments would help improve readability / checkability?
```suggestion
        // 1, 2     
        // xx = x1 * x2
        // yy = y1 * y2
        let xx = &self.x * other_x;
        let yy = &self.y * other_y;
        // 4, 5, 6, 7, 8
        // xy_pairs = (x1 + y1) * (x2 + y2) - (xx + yy)
        let xy_pairs = ((&self.x + &self.y) * &(other_x + other_y)) - (&xx + &yy);
        // 8,9,10,11
        // xz_pairs = (x2 * z1) + x1
        // yz_pairs = (y2 * z1) + y1
        let xz_pairs = (other_x * &self.z) + &self.x;
        let yz_pairs = (other_y * &self.z) + &self.y;
...
```

2021-01-09 07:37 UTC, ValarDragon commented on src/groups/curves/short_weierstrass/mod.rs
> +    |mut this: &'a ProjectiveVar<P, F>, mut other: &'a ProjectiveVar<P, F>| {
Can there be a comment for what this is doing? Without the above `Complete addition formula` comment, I have no idea what the goal of this code is

2021-01-09 22:38 UTC, Pratyush commented on src/groups/curves/short_weierstrass/mod.rs
> +        let z = (&yy_p_bz3 * &yz_pairs) + xy_pairs * xx3_p_azz; // 31, 32, 33
if the only change is to rename self.x and other.x to x1 and x2, then I can make that change in code directly.

2021-01-09 22:45 UTC, ValarDragon commented on src/groups/curves/short_weierstrass/mod.rs
> +        let z = (&yy_p_bz3 * &yz_pairs) + xy_pairs * xx3_p_azz; // 31, 32, 33
oh cool, lets do that then

2021-01-09 22:51 UTC, Pratyush commented on src/groups/curves/short_weierstrass/mod.rs
> +        let z = (&yy_p_bz3 * &yz_pairs) + xy_pairs * xx3_p_azz; // 31, 32, 33
Done

2021-01-09 22:52 UTC, Pratyush commented on src/groups/curves/short_weierstrass/mod.rs
> +    |mut this: &'a ProjectiveVar<P, F>, mut other: &'a ProjectiveVar<P, F>| {
Done

2021-01-09 22:55 UTC, Pratyush commented on src/groups/curves/short_weierstrass/mod.rs
> +        // (https://eprint.iacr.org/2015/1060).
Done. (thanks for the review, the code is of much better quality now =))

2021-01-09 23:06 UTC, ValarDragon approved these changes
LGTM! Thanks for improving the code quality for all the code touched

2021-01-10 21:18 UTC, merged