Publicize non-zero weierstrass affine variables
arkworks-rs/r1cs-std pull request #84
Opened 2021-11-18 01:18 UTC by alex-ozdemir

## Description

I've found these to be useful for a recent project.

I also added an `EqGadget` implementation and a test.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests 
- [x] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

2021-11-19 22:09 UTC, Pratyush commented on src/groups/curves/short_weierstrass/mod.rs
> +/// short-weierstrass curves in affine coordinates that **are not** equal to zero.
Can you add a warning stating that the `ProjectiveCurve` API should be the preferred one?

2021-11-19 22:11 UTC, Pratyush reviewed
I'm curious, what was your use case for the affine coordinates? Our projective coordinate impl is safe by default, but doesn't incur the overhead of the expensive complete formulae in scalar multiplication (by safely using on the incomplete affine formulae only when needed)

2021-11-28 20:47 UTC, alex-ozdemir commented on src/groups/curves/short_weierstrass/mod.rs
> +/// short-weierstrass curves in affine coordinates that **are not** equal to zero.
Yes! Done in 3ad9ca0.

2021-11-28 20:53 UTC, alex-ozdemir commented
Sorry for the delay; I was out-of-town.

We were working with a prime-order curve and had a large computation that could produce intermediate zeros with only negligible probability.

2021-12-31 12:20 UTC, mmagician requested changes

2021-12-31 12:20 UTC, mmagician commented on src/groups/curves/short_weierstrass/non_zero_affine.rs
> +    ) -> Result<(), SynthesisError> {
```suggestion
    fn enforce_equal(&self, other: &Self) -> Result<(), SynthesisError> {
```

2021-12-31 12:20 UTC, mmagician commented on src/groups/curves/short_weierstrass/non_zero_affine.rs
> +        let a_multiples: Vec<NonZeroAffineVar::<G1Parameters, FpVar<Fq>>> =
```suggestion
        let a_multiples: Vec<NonZeroAffineVar<G1Parameters, FpVar<Fq>>> =
```

2021-12-31 12:20 UTC, mmagician commented on src/groups/curves/short_weierstrass/non_zero_affine.rs
> +            .collect();
```suggestion
                .take(n)
                .collect();
```

2021-12-31 12:20 UTC, mmagician commented on src/groups/curves/short_weierstrass/non_zero_affine.rs
> +            .map(|i| a_multiples[i].add_unchecked(&a_multiples[n-i-1]).unwrap())
```suggestion
        let all_equal: Vec<NonZeroAffineVar<G1Parameters, FpVar<Fq>>> = (0..n / 2)
            .map(|i| {
                a_multiples[i]
                    .add_unchecked(&a_multiples[n - i - 1])
                    .unwrap()
            )}
```

2021-12-31 12:20 UTC, mmagician commented on src/groups/curves/short_weierstrass/non_zero_affine.rs
> +            a_multiples[i].enforce_not_equal(&a_multiples[i+1]).unwrap();
```suggestion
        for i in 0..n - 1 {
            a_multiples[i]
                .enforce_not_equal(&a_multiples[i + 1])
                .unwrap();
```

2021-12-31 12:20 UTC, mmagician commented on src/groups/curves/short_weierstrass/non_zero_affine.rs
> +            all_equal[i].enforce_equal(&all_equal[i+1]).unwrap();
```suggestion
        for i in 0..all_equal.len() - 1 {
            all_equal[i].enforce_equal(&all_equal[i + 1]).unwrap();
```

2021-12-31 12:25 UTC, mmagician commented on src/groups/curves/short_weierstrass/non_zero_affine.rs
> +            )}
```suggestion
            })
```

2021-12-31 12:33 UTC, mmagician approved these changes

2022-03-08 08:43 UTC, merged